version: 2

models:
  - name: transform
    columns:
      - name: tpep_pickup_datetime
        tests:
          - not_null
      - name: tpep_dropoff_datetime
        tests:
          - not_null
      - name: passenger_count
        tests:
          - not_null
          - accepted_values:
              values: [1, 2, 3, 4, 5, 6]
      - name: trip_distance
        tests:
          - not_null
      - name: total_amount
        tests:
          - not_null
      - name: payment_type
        tests:
          - not_null
          - accepted_values:
              values: [1, 2, 3, 4, 5, 6] # Assuming payment_type is numerical based on common taxi datasets
      - name: trip_duration_minutes
        tests:
          - not_null
    tests:
      - dbt_utils.expression_is_true:
          expression: "tpep_dropoff_datetime > tpep_pickup_datetime"
      - dbt_expectations.expression_is_true:
          expression: "trip_distance >= 0"
      - dbt_expectations.expression_is_true:
          expression: "total_amount >= 0"
      - dbt_expectations.expression_is_true:
          expression: "trip_duration_minutes >= 0"